"""Ensure .env exists and OLLAMA_BASE_URL is set for Docker → host Ollama."""

from __future__ import annotations

import re
from pathlib import Path

from .util import (
    DOCKER_HOST_OLLAMA,
    info,
    is_linux,
    ok,
    warn,
)


OLLAMA_KEY = "OLLAMA_BASE_URL"


def default_ollama_base_url() -> str:
    # Docker Desktop (macOS/Windows) and Linux with host-gateway both use this.
    return DOCKER_HOST_OLLAMA


def ensure_env_file(repo_root: Path, *, yes: bool = False, dry_run: bool = False) -> Path:
    """Copy .env.example → .env if missing; return path to .env."""
    env_path = repo_root / ".env"
    example = repo_root / ".env.example"

    if env_path.is_file():
        ok(f".env present: {env_path}")
        return env_path

    if not example.is_file():
        warn(".env.example missing; creating a minimal .env")
        content = f"# Generated by routism_cli\n{OLLAMA_KEY}={default_ollama_base_url()}\n"
        if dry_run:
            info("[dry-run] would create .env")
            return env_path
        env_path.write_text(content, encoding="utf-8")
        ok(f"Created {env_path}")
        return env_path

    if dry_run:
        info(f"[dry-run] would copy {example.name} → .env")
        return env_path

    content = example.read_text(encoding="utf-8")
    env_path.write_text(content, encoding="utf-8")
    ok(f"Created {env_path} from .env.example")
    return env_path


def _set_or_replace_key(text: str, key: str, value: str) -> str:
    pattern = re.compile(rf"(?m)^\s*{re.escape(key)}\s*=.*$")
    line = f"{key}={value}"
    if pattern.search(text):
        return pattern.sub(line, text)
    # append under an Engine section if possible
    if not text.endswith("\n"):
        text += "\n"
    if "OLLAMA" not in text.upper():
        text += "\n# --- Engine (Ollama on host) ---\n"
    text += line + "\n"
    return text


def ensure_ollama_base_url(
    repo_root: Path,
    *,
    yes: bool = False,
    dry_run: bool = False,
) -> str:
    """Ensure OLLAMA_BASE_URL is set for containers talking to host Ollama."""
    env_path = ensure_env_file(repo_root, yes=yes, dry_run=dry_run)
    desired = default_ollama_base_url()

    if dry_run and not env_path.is_file():
        info(f"[dry-run] would set {OLLAMA_KEY}={desired}")
        return desired

    if not env_path.is_file():
        # ensure_env_file should have created it unless dry-run
        if dry_run:
            return desired
        raise RuntimeError("expected .env after ensure_env_file")

    text = env_path.read_text(encoding="utf-8")
    m = re.search(rf"(?m)^\s*{re.escape(OLLAMA_KEY)}\s*=\s*(.*)$", text)
    if m:
        current = m.group(1).strip().strip("\"'")
        if current:
            ok(f"{OLLAMA_KEY}={current}")
            if is_linux() and "host.docker.internal" not in current:
                info(
                    "On Linux, docker-compose.yml adds host-gateway so "
                    "host.docker.internal resolves to the host."
                )
            return current

    new_text = _set_or_replace_key(text, OLLAMA_KEY, desired)
    if dry_run:
        info(f"[dry-run] would set {OLLAMA_KEY}={desired} in .env")
        return desired
    env_path.write_text(new_text, encoding="utf-8")
    ok(f"Set {OLLAMA_KEY}={desired} in .env")
    return desired


def agent_env_snippet() -> str:
    return """# Point your coding agent / OpenAI SDK at Routism:
export OPENAI_BASE_URL="http://localhost:8000/v1"
export OPENAI_API_KEY="rtm_…"   # create a key in the dashboard (API keys)
# model: routism-ultra
# Client timeout: 300–600 seconds (orchestration is multi-step)"""
